### ISSUE TITLE
#2 옷 수정시 옷장은 옷장목록 안에서만 가능하게 해야함

### ISSUE THREAD

**Issue by Dcaffein** [KWEBofficial/stylevillage-server#19]
현재는 옷 수정시 내 옷장인지 점검하는 로직이 없음
옷장 리스트업 브랜치 머지 이후에 closetRepository의 메서드를 이용해서 내 옷장인지 점검하기

옷 생성 역시 closet이 user의 closet인지 확인해야 함!

**Comment by isseul** [comment]
옷 수정/삭제 시 입력한 옷장이 존재하는지도 확인해야 함. (옷장이 존재해야 내 옷장인지 점검할 수 있겠지만)
